version: '3.5'
services:
  base:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PIHOLE_VERSION=${PIHOLE_VERSION}
        - TAG=${IMAGE_VERSION}
    image: ${DOCKER_REPO}/${DOCKER_IMAGE}:${IMAGE_VERSION}
  dev:
    env_file:
      - .env
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - PIHOLE_VERSION=${PIHOLE_VERSION}
        - TAG=${IMAGE_VERSION}
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
